// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.CreditNote
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "100")]
        #pragma warning disable CS1591
        OneZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "200")]
        #pragma warning disable CS1591
        TwoZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "300")]
        #pragma warning disable CS1591
        ThreeZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "500")]
        #pragma warning disable CS1591
        FiveZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "750")]
        #pragma warning disable CS1591
        SevenFiveZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "1000")]
        #pragma warning disable CS1591
        OneZeroZeroZero,
        #pragma warning restore CS1591
    }
}
