// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.InvoicePos
{
    /// <summary>
    /// Builds and executes requests for operations under \InvoicePos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class InvoicePosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvoicePosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/InvoicePos{?id*,invoice%5Bid%5D*,invoice%5BobjectName%5D*,part%5Bid%5D*,part%5BobjectName%5D*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvoicePosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/InvoicePos{?id*,invoice%5Bid%5D*,invoice%5BobjectName%5D*,part%5Bid%5D*,part%5BobjectName%5D*}", rawUrl)
        {
        }
        /// <summary>
        /// There are a multitude of parameter which can be used to filter.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.InvoicePos.InvoicePosGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.InvoicePos.InvoicePosGetResponse?> GetAsInvoicePosGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder.InvoicePosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.InvoicePos.InvoicePosGetResponse> GetAsInvoicePosGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder.InvoicePosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.InvoicePos.InvoicePosGetResponse>(requestInfo, global::SevDesk.Api.V2.InvoicePos.InvoicePosGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// There are a multitude of parameter which can be used to filter.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.InvoicePos.InvoicePosResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsInvoicePosGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.InvoicePos.InvoicePosResponse?> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder.InvoicePosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.InvoicePos.InvoicePosResponse> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder.InvoicePosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.InvoicePos.InvoicePosResponse>(requestInfo, global::SevDesk.Api.V2.InvoicePos.InvoicePosResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// There are a multitude of parameter which can be used to filter.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder.InvoicePosRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder.InvoicePosRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// There are a multitude of parameter which can be used to filter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class InvoicePosRequestBuilderGetQueryParameters 
        {
            /// <summary>Retrieve all InvoicePos with this InvoicePos id</summary>
            [QueryParameter("id")]
            public double? Id { get; set; }
            /// <summary>Retrieve all invoices positions with this invoice. Must be provided with invoice[objectName]</summary>
            [QueryParameter("invoice%5Bid%5D")]
            public double? Invoiceid { get; set; }
            /// <summary>Only required if invoice[id] was provided. &apos;Invoice&apos; should be used as value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("invoice%5BobjectName%5D")]
            public string? InvoiceobjectName { get; set; }
#nullable restore
#else
            [QueryParameter("invoice%5BobjectName%5D")]
            public string InvoiceobjectName { get; set; }
#endif
            /// <summary>Retrieve all invoices positions with this part. Must be provided with part[objectName]</summary>
            [QueryParameter("part%5Bid%5D")]
            public double? Partid { get; set; }
            /// <summary>Only required if part[id] was provided. &apos;Part&apos; should be used as value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("part%5BobjectName%5D")]
            public string? PartobjectName { get; set; }
#nullable restore
#else
            [QueryParameter("part%5BobjectName%5D")]
            public string PartobjectName { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class InvoicePosRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SevDesk.Api.V2.InvoicePos.InvoicePosRequestBuilder.InvoicePosRequestBuilderGetQueryParameters>
        {
        }
    }
}
