// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SevDesk.Api.V2.Order.Factory.CreateContractNoteFromOrder;
using SevDesk.Api.V2.Order.Factory.CreatePackingListFromOrder;
using SevDesk.Api.V2.Order.Factory.SaveOrder;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SevDesk.Api.V2.Order.Factory
{
    /// <summary>
    /// Builds and executes requests for operations under \Order\Factory
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class FactoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The createContractNoteFromOrder property</summary>
        public global::SevDesk.Api.V2.Order.Factory.CreateContractNoteFromOrder.CreateContractNoteFromOrderRequestBuilder CreateContractNoteFromOrder
        {
            get => new global::SevDesk.Api.V2.Order.Factory.CreateContractNoteFromOrder.CreateContractNoteFromOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createPackingListFromOrder property</summary>
        public global::SevDesk.Api.V2.Order.Factory.CreatePackingListFromOrder.CreatePackingListFromOrderRequestBuilder CreatePackingListFromOrder
        {
            get => new global::SevDesk.Api.V2.Order.Factory.CreatePackingListFromOrder.CreatePackingListFromOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saveOrder property</summary>
        public global::SevDesk.Api.V2.Order.Factory.SaveOrder.SaveOrderRequestBuilder SaveOrder
        {
            get => new global::SevDesk.Api.V2.Order.Factory.SaveOrder.SaveOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Order.Factory.FactoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FactoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Order/Factory", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Order.Factory.FactoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FactoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Order/Factory", rawUrl)
        {
        }
    }
}
