// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Invoice.Item.BookAmount
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Define a type for the booking.&lt;br&gt;    The following type abbreviations are available (abbreviation &lt;-&gt; meaning).&lt;br&gt;    &lt;ul&gt;    &lt;li&gt;N &lt;-&gt; Normal booking / partial booking&lt;/li&gt;    &lt;li&gt;CB &lt;-&gt; Reduced amount due to discount (skonto)&lt;/li&gt;    &lt;li&gt;CF &lt;-&gt; Reduced/Higher amount due to currency fluctuations (deprecated)&lt;/li&gt;    &lt;li&gt;O &lt;-&gt; Reduced/Higher amount due to other reasons&lt;/li&gt;    &lt;li&gt;OF &lt;-&gt; Higher amount due to reminder charges&lt;/li&gt;    &lt;li&gt;MTC &lt;-&gt; Reduced amount due to the monetary traffic costs&lt;/li&gt;    &lt;/ul&gt;</summary>
    public enum BookAmountPutRequestBody_type
    {
        [EnumMember(Value = "N")]
        #pragma warning disable CS1591
        N,
        #pragma warning restore CS1591
        [EnumMember(Value = "CB")]
        #pragma warning disable CS1591
        CB,
        #pragma warning restore CS1591
        [EnumMember(Value = "CF")]
        #pragma warning disable CS1591
        CF,
        #pragma warning restore CS1591
        [EnumMember(Value = "O")]
        #pragma warning disable CS1591
        O,
        #pragma warning restore CS1591
        [EnumMember(Value = "OF")]
        #pragma warning disable CS1591
        OF,
        #pragma warning restore CS1591
        [EnumMember(Value = "MTC")]
        #pragma warning disable CS1591
        MTC,
        #pragma warning restore CS1591
    }
}
