// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Defines if this check account is the default account.</summary>
    public enum CreateFileImportAccountResponse_defaultAccount
    {
        [EnumMember(Value = "0")]
        #pragma warning disable CS1591
        Zero,
        #pragma warning restore CS1591
        [EnumMember(Value = "1")]
        #pragma warning disable CS1591
        One,
        #pragma warning restore CS1591
    }
}
