// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Type which was used to send the creditNote. IMPORTANT: Please refer to the creditNote section of the     *     API-Overview to understand how this attribute can be used before using it!</summary>
    public enum Model_creditNote_sendType
    {
        [EnumMember(Value = "VPR")]
        #pragma warning disable CS1591
        VPR,
        #pragma warning restore CS1591
        [EnumMember(Value = "VPDF")]
        #pragma warning disable CS1591
        VPDF,
        #pragma warning restore CS1591
        [EnumMember(Value = "VM")]
        #pragma warning disable CS1591
        VM,
        #pragma warning restore CS1591
        [EnumMember(Value = "VP")]
        #pragma warning disable CS1591
        VP,
        #pragma warning restore CS1591
    }
}
