// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SevDesk.Api.V2.Models
{
    /// <summary>
    /// Order model
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class Model_OrderUpdate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Complete address of the recipient including name, street, city, zip and country.&lt;br&gt;     Line breaks can be used and will be displayed on the invoice pdf.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>Can be omitted as complete address is defined in address attribute</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_addressCountry? AddressCountry { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_addressCountry AddressCountry { get; set; }
#endif
        /// <summary>The contact used in the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_contact? Contact { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_contact Contact { get; set; }
#endif
        /// <summary>The user who acts as a contact person for the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_contactPerson? ContactPerson { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_contactPerson ContactPerson { get; set; }
#endif
        /// <summary>Date of order creation</summary>
        public DateTimeOffset? Create { get; private set; }
        /// <summary>Will be filled automatically by our system and can&apos;t be changed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_createUser? CreateUser { get; private set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_createUser CreateUser { get; private set; }
#endif
        /// <summary>Currency used in the order. Needs to be currency code according to ISO-4217</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Internal note of the customer. Contains data entered into field &apos;Referenz/Bestellnummer&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerInternalNote { get; set; }
#nullable restore
#else
        public string CustomerInternalNote { get; set; }
#endif
        /// <summary>Delivery terms of the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryTerms { get; set; }
#nullable restore
#else
        public string DeliveryTerms { get; set; }
#endif
        /// <summary>Certain html tags can be used here to format your text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FootText { get; set; }
#nullable restore
#else
        public string FootText { get; set; }
#endif
        /// <summary>Normally consist of prefix plus the order number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Header { get; set; }
#nullable restore
#else
        public string Header { get; set; }
#endif
        /// <summary>Certain html tags can be used here to format your text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeadText { get; set; }
#nullable restore
#else
        public string HeadText { get; set; }
#endif
        /// <summary>The order id</summary>
        public int? Id { get; private set; }
        /// <summary>The order object name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectName { get; private set; }
#nullable restore
#else
        public string ObjectName { get; private set; }
#endif
        /// <summary>Needs to be provided as timestamp or dd.mm.yyyy</summary>
        public DateTimeOffset? OrderDate { get; set; }
        /// <summary>The order number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderNumber { get; set; }
#nullable restore
#else
        public string OrderNumber { get; set; }
#endif
        /// <summary>Type of the order. For more information on the different types, check    &lt;a href=&apos;#tag/Order/Types-and-status-of-orders&apos;&gt;this&lt;/a&gt;</summary>
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_orderType? OrderType { get; set; }
        /// <summary>Object from which the order was created. For example an offer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_origin? Origin { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_origin Origin { get; set; }
#endif
        /// <summary>Payment terms of the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentTerms { get; set; }
#nullable restore
#else
        public string PaymentTerms { get; set; }
#endif
        /// <summary>The date the order was sent to the customer</summary>
        public DateTimeOffset? SendDate { get; set; }
        /// <summary>Type which was used to send the order. IMPORTANT: Please refer to the order section of the     *     API-Overview to understand how this attribute can be used before using it!</summary>
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_sendType? SendType { get; set; }
        /// <summary>Client to which order belongs. Will be filled automatically</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_sevClient? SevClient { get; private set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_sevClient SevClient { get; private set; }
#endif
        /// <summary>If true, the net amount of each position will be shown on the order. Otherwise gross amount</summary>
        public bool? ShowNet { get; set; }
        /// <summary>Defines if the client uses the small settlement scheme.    If yes, the order must not contain any vat</summary>
        public bool? SmallSettlement { get; set; }
        /// <summary>Please have a look in     &lt;a href=&apos;#tag/Order/Types-and-status-of-orders&apos;&gt;status of orders&lt;/a&gt;    to see what the different status codes mean</summary>
        public int? Status { get; set; }
        /// <summary>Sum of all discounts in the order</summary>
        public double? SumDiscounts { get; private set; }
        /// <summary>Discounts sum of the order in the foreign currency</summary>
        public double? SumDiscountsForeignCurrency { get; private set; }
        /// <summary>Gross sum of the order</summary>
        public double? SumGross { get; private set; }
        /// <summary>Gross sum of the order in the foreign currency</summary>
        public double? SumGrossForeignCurrency { get; private set; }
        /// <summary>Net sum of the order</summary>
        public double? SumNet { get; private set; }
        /// <summary>Net sum of the order in the foreign currency</summary>
        public double? SumNetForeignCurrency { get; private set; }
        /// <summary>Tax sum of the order</summary>
        public double? SumTax { get; private set; }
        /// <summary>Tax sum of the order in the foreign currency</summary>
        public double? SumTaxForeignCurrency { get; private set; }
        /// <summary>This is not used anymore. Use the taxRate of the individual positions instead.</summary>
        public double? TaxRate { get; set; }
        /// <summary>**Use this in sevdesk-Update 2.0 (replaces taxType / taxSet).**</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxRule? TaxRule { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxRule TaxRule { get; set; }
#endif
        /// <summary>**Use this in sevdesk-Update 1.0 (instead of taxRule).**Tax set of the order. Needs to be added if you chose the tax type custom</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxSet? TaxSet { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxSet TaxSet { get; set; }
#endif
        /// <summary>A common tax text would be &apos;Umsatzsteuer 19%&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxText { get; set; }
#nullable restore
#else
        public string TaxText { get; set; }
#endif
        /// <summary>**Use this in sevdesk-Update 1.0 (instead of taxRule).**Tax type of the order.There are four tax types:1. default - Umsatzsteuer ausweisen2. eu - Steuerfreie innergemeinschaftliche Lieferung (Europäische Union)3. noteu - Steuerschuldnerschaft des Leistungsempfängers (außerhalb EU, z. B. Schweiz)4. custom - Using custom tax set5. ss - Not subject to VAT according to §19 1 UStGTax rates are heavily connected to the tax type used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxType { get; set; }
#nullable restore
#else
        public string TaxType { get; set; }
#endif
        /// <summary>Date of last order update</summary>
        public DateTimeOffset? Update { get; private set; }
        /// <summary>Version of the order.&lt;br&gt;    Can be used if you have multiple drafts for the same order.&lt;br&gt;    Should start with 0</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Models.Model_OrderUpdate"/> and sets the default values.
        /// </summary>
        public Model_OrderUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Models.Model_OrderUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SevDesk.Api.V2.Models.Model_OrderUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SevDesk.Api.V2.Models.Model_OrderUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "addressCountry", n => { AddressCountry = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_addressCountry>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_addressCountry.CreateFromDiscriminatorValue); } },
                { "contact", n => { Contact = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_contact>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_contact.CreateFromDiscriminatorValue); } },
                { "contactPerson", n => { ContactPerson = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_contactPerson>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_contactPerson.CreateFromDiscriminatorValue); } },
                { "create", n => { Create = n.GetDateTimeOffsetValue(); } },
                { "createUser", n => { CreateUser = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_createUser>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_createUser.CreateFromDiscriminatorValue); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "customerInternalNote", n => { CustomerInternalNote = n.GetStringValue(); } },
                { "deliveryTerms", n => { DeliveryTerms = n.GetStringValue(); } },
                { "footText", n => { FootText = n.GetStringValue(); } },
                { "headText", n => { HeadText = n.GetStringValue(); } },
                { "header", n => { Header = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "objectName", n => { ObjectName = n.GetStringValue(); } },
                { "orderDate", n => { OrderDate = n.GetDateTimeOffsetValue(); } },
                { "orderNumber", n => { OrderNumber = n.GetStringValue(); } },
                { "orderType", n => { OrderType = n.GetEnumValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_orderType>(); } },
                { "origin", n => { Origin = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_origin>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_origin.CreateFromDiscriminatorValue); } },
                { "paymentTerms", n => { PaymentTerms = n.GetStringValue(); } },
                { "sendDate", n => { SendDate = n.GetDateTimeOffsetValue(); } },
                { "sendType", n => { SendType = n.GetEnumValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_sendType>(); } },
                { "sevClient", n => { SevClient = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_sevClient>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_sevClient.CreateFromDiscriminatorValue); } },
                { "showNet", n => { ShowNet = n.GetBoolValue(); } },
                { "smallSettlement", n => { SmallSettlement = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "sumDiscounts", n => { SumDiscounts = n.GetDoubleValue(); } },
                { "sumDiscountsForeignCurrency", n => { SumDiscountsForeignCurrency = n.GetDoubleValue(); } },
                { "sumGross", n => { SumGross = n.GetDoubleValue(); } },
                { "sumGrossForeignCurrency", n => { SumGrossForeignCurrency = n.GetDoubleValue(); } },
                { "sumNet", n => { SumNet = n.GetDoubleValue(); } },
                { "sumNetForeignCurrency", n => { SumNetForeignCurrency = n.GetDoubleValue(); } },
                { "sumTax", n => { SumTax = n.GetDoubleValue(); } },
                { "sumTaxForeignCurrency", n => { SumTaxForeignCurrency = n.GetDoubleValue(); } },
                { "taxRate", n => { TaxRate = n.GetDoubleValue(); } },
                { "taxRule", n => { TaxRule = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxRule>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxRule.CreateFromDiscriminatorValue); } },
                { "taxSet", n => { TaxSet = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxSet>(global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxSet.CreateFromDiscriminatorValue); } },
                { "taxText", n => { TaxText = n.GetStringValue(); } },
                { "taxType", n => { TaxType = n.GetStringValue(); } },
                { "update", n => { Update = n.GetDateTimeOffsetValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_addressCountry>("addressCountry", AddressCountry);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_contact>("contact", Contact);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_contactPerson>("contactPerson", ContactPerson);
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("customerInternalNote", CustomerInternalNote);
            writer.WriteStringValue("deliveryTerms", DeliveryTerms);
            writer.WriteStringValue("footText", FootText);
            writer.WriteStringValue("header", Header);
            writer.WriteStringValue("headText", HeadText);
            writer.WriteDateTimeOffsetValue("orderDate", OrderDate);
            writer.WriteStringValue("orderNumber", OrderNumber);
            writer.WriteEnumValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_orderType>("orderType", OrderType);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_origin>("origin", Origin);
            writer.WriteStringValue("paymentTerms", PaymentTerms);
            writer.WriteDateTimeOffsetValue("sendDate", SendDate);
            writer.WriteEnumValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_sendType>("sendType", SendType);
            writer.WriteBoolValue("showNet", ShowNet);
            writer.WriteBoolValue("smallSettlement", SmallSettlement);
            writer.WriteIntValue("status", Status);
            writer.WriteDoubleValue("taxRate", TaxRate);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxRule>("taxRule", TaxRule);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_OrderUpdate_taxSet>("taxSet", TaxSet);
            writer.WriteStringValue("taxText", TaxText);
            writer.WriteStringValue("taxType", TaxType);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
