// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Type of the order. For more information on the different types, check    &lt;a href=&apos;#tag/Order/Types-and-status-of-orders&apos;&gt;this&lt;/a&gt; </summary>
    public enum Model_Order_orderType
    {
        [EnumMember(Value = "AN")]
        #pragma warning disable CS1591
        AN,
        #pragma warning restore CS1591
        [EnumMember(Value = "AB")]
        #pragma warning disable CS1591
        AB,
        #pragma warning restore CS1591
        [EnumMember(Value = "LI")]
        #pragma warning disable CS1591
        LI,
        #pragma warning restore CS1591
    }
}
