// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Please have a look in our     &lt;a href=&apos;#tag/Invoice/Types-and-status-of-invoices&apos;&gt;Types and status of invoices&lt;/a&gt;     to see what the different status codes mean</summary>
    public enum Model_InvoiceResponse_status
    {
        [EnumMember(Value = "50")]
        #pragma warning disable CS1591
        FiveZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "100")]
        #pragma warning disable CS1591
        OneZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "200")]
        #pragma warning disable CS1591
        TwoZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "750")]
        #pragma warning disable CS1591
        SevenFiveZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "1000")]
        #pragma warning disable CS1591
        OneZeroZeroZero,
        #pragma warning restore CS1591
    }
}
