// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SevDesk.Api.V2.Models
{
    /// <summary>
    /// Invoice position model
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class Model_InvoicePos : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Date of invoice position creation</summary>
        public DateTimeOffset? Create { get; private set; }
        /// <summary>An optional discount of the position.</summary>
        public float? Discount { get; set; }
        /// <summary>The invoice position id. &lt;span style=&apos;color:red&apos;&gt;Required&lt;/span&gt; if you want to update an invoice position for an existing invoice</summary>
        public int? Id { get; set; }
        /// <summary>The invoice to which the position belongs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_invoice? Invoice { get; private set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_invoice Invoice { get; private set; }
#endif
        /// <summary>The mapAll property</summary>
        public bool? MapAll { get; set; }
        /// <summary>Name of the article/part.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The invoice position object name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectName { get; set; }
#nullable restore
#else
        public string ObjectName { get; set; }
#endif
        /// <summary>Part from your inventory which is used in the position.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_part? Part { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_part Part { get; set; }
#endif
        /// <summary>Position number of your position. Can be used to order multiple positions.</summary>
        public int? PositionNumber { get; set; }
        /// <summary>Price of the article/part. Is either gross or net, depending on the sevdesk account setting.</summary>
        public float? Price { get; set; }
        /// <summary>Gross price of the part</summary>
        public float? PriceGross { get; set; }
        /// <summary>Net price of the part</summary>
        public float? PriceNet { get; private set; }
        /// <summary>Tax on the price of the part</summary>
        public float? PriceTax { get; set; }
        /// <summary>Quantity of the article/part</summary>
        public float? Quantity { get; set; }
        /// <summary>Client to which invoice position belongs. Will be filled automatically</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_sevClient? SevClient { get; private set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_sevClient SevClient { get; private set; }
#endif
        /// <summary>Discount sum of the position</summary>
        public float? SumDiscount { get; private set; }
        /// <summary>Gross accounting sum of the position</summary>
        public float? SumGrossAccounting { get; private set; }
        /// <summary>Net accounting sum of the position</summary>
        public float? SumNetAccounting { get; private set; }
        /// <summary>Tax accounting sum of the position</summary>
        public float? SumTaxAccounting { get; private set; }
        /// <summary>Tax rate of the position.</summary>
        public float? TaxRate { get; set; }
        /// <summary>A text describing your position.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The unit in which the positions part is measured</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_unity? Unity { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_InvoicePos_unity Unity { get; set; }
#endif
        /// <summary>Date of last invoice position update</summary>
        public DateTimeOffset? Update { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Models.Model_InvoicePos"/> and sets the default values.
        /// </summary>
        public Model_InvoicePos()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Models.Model_InvoicePos"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SevDesk.Api.V2.Models.Model_InvoicePos CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SevDesk.Api.V2.Models.Model_InvoicePos();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "create", n => { Create = n.GetDateTimeOffsetValue(); } },
                { "discount", n => { Discount = n.GetFloatValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "invoice", n => { Invoice = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_InvoicePos_invoice>(global::SevDesk.Api.V2.Models.Model_InvoicePos_invoice.CreateFromDiscriminatorValue); } },
                { "mapAll", n => { MapAll = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "objectName", n => { ObjectName = n.GetStringValue(); } },
                { "part", n => { Part = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_InvoicePos_part>(global::SevDesk.Api.V2.Models.Model_InvoicePos_part.CreateFromDiscriminatorValue); } },
                { "positionNumber", n => { PositionNumber = n.GetIntValue(); } },
                { "price", n => { Price = n.GetFloatValue(); } },
                { "priceGross", n => { PriceGross = n.GetFloatValue(); } },
                { "priceNet", n => { PriceNet = n.GetFloatValue(); } },
                { "priceTax", n => { PriceTax = n.GetFloatValue(); } },
                { "quantity", n => { Quantity = n.GetFloatValue(); } },
                { "sevClient", n => { SevClient = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_InvoicePos_sevClient>(global::SevDesk.Api.V2.Models.Model_InvoicePos_sevClient.CreateFromDiscriminatorValue); } },
                { "sumDiscount", n => { SumDiscount = n.GetFloatValue(); } },
                { "sumGrossAccounting", n => { SumGrossAccounting = n.GetFloatValue(); } },
                { "sumNetAccounting", n => { SumNetAccounting = n.GetFloatValue(); } },
                { "sumTaxAccounting", n => { SumTaxAccounting = n.GetFloatValue(); } },
                { "taxRate", n => { TaxRate = n.GetFloatValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "unity", n => { Unity = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_InvoicePos_unity>(global::SevDesk.Api.V2.Models.Model_InvoicePos_unity.CreateFromDiscriminatorValue); } },
                { "update", n => { Update = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("discount", Discount);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("mapAll", MapAll);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("objectName", ObjectName);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_InvoicePos_part>("part", Part);
            writer.WriteIntValue("positionNumber", PositionNumber);
            writer.WriteFloatValue("price", Price);
            writer.WriteFloatValue("priceGross", PriceGross);
            writer.WriteFloatValue("priceTax", PriceTax);
            writer.WriteFloatValue("quantity", Quantity);
            writer.WriteFloatValue("taxRate", TaxRate);
            writer.WriteStringValue("text", Text);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_InvoicePos_unity>("unity", Unity);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
