// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Please have a look in     &lt;a href=&apos;#tag/CreditNote/Status-of-credit-notes&apos;&gt;status of credit note&lt;/a&gt;    to see what the different status codes mean</summary>
    public enum Model_creditNoteUpdate_status
    {
        [EnumMember(Value = "100")]
        #pragma warning disable CS1591
        OneZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "200")]
        #pragma warning disable CS1591
        TwoZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "750")]
        #pragma warning disable CS1591
        SevenFiveZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "1000")]
        #pragma warning disable CS1591
        OneZeroZeroZero,
        #pragma warning restore CS1591
    }
}
