// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SevDesk.Api.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class SaveCreditNote : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>creditNote model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_creditNote? CreditNote { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_creditNote CreditNote { get; set; }
#endif
        /// <summary>The creditNotePosDelete property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.SaveCreditNote_creditNotePosDelete? CreditNotePosDelete { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.SaveCreditNote_creditNotePosDelete CreditNotePosDelete { get; set; }
#endif
        /// <summary>The creditNotePosSave property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SevDesk.Api.V2.Models.Model_creditNotePos>? CreditNotePosSave { get; set; }
#nullable restore
#else
        public List<global::SevDesk.Api.V2.Models.Model_creditNotePos> CreditNotePosSave { get; set; }
#endif
        /// <summary>The discountDelete property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.SaveCreditNote_discountDelete? DiscountDelete { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.SaveCreditNote_discountDelete DiscountDelete { get; set; }
#endif
        /// <summary>The discountSave property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.SaveCreditNote_discountSave? DiscountSave { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.SaveCreditNote_discountSave DiscountSave { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Models.SaveCreditNote"/> and sets the default values.
        /// </summary>
        public SaveCreditNote()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Models.SaveCreditNote"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SevDesk.Api.V2.Models.SaveCreditNote CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SevDesk.Api.V2.Models.SaveCreditNote();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creditNote", n => { CreditNote = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_creditNote>(global::SevDesk.Api.V2.Models.Model_creditNote.CreateFromDiscriminatorValue); } },
                { "creditNotePosDelete", n => { CreditNotePosDelete = n.GetObjectValue<global::SevDesk.Api.V2.Models.SaveCreditNote_creditNotePosDelete>(global::SevDesk.Api.V2.Models.SaveCreditNote_creditNotePosDelete.CreateFromDiscriminatorValue); } },
                { "creditNotePosSave", n => { CreditNotePosSave = n.GetCollectionOfObjectValues<global::SevDesk.Api.V2.Models.Model_creditNotePos>(global::SevDesk.Api.V2.Models.Model_creditNotePos.CreateFromDiscriminatorValue)?.AsList(); } },
                { "discountDelete", n => { DiscountDelete = n.GetObjectValue<global::SevDesk.Api.V2.Models.SaveCreditNote_discountDelete>(global::SevDesk.Api.V2.Models.SaveCreditNote_discountDelete.CreateFromDiscriminatorValue); } },
                { "discountSave", n => { DiscountSave = n.GetObjectValue<global::SevDesk.Api.V2.Models.SaveCreditNote_discountSave>(global::SevDesk.Api.V2.Models.SaveCreditNote_discountSave.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_creditNote>("creditNote", CreditNote);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.SaveCreditNote_creditNotePosDelete>("creditNotePosDelete", CreditNotePosDelete);
            writer.WriteCollectionOfObjectValues<global::SevDesk.Api.V2.Models.Model_creditNotePos>("creditNotePosSave", CreditNotePosSave);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.SaveCreditNote_discountDelete>("discountDelete", DiscountDelete);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.SaveCreditNote_discountSave>("discountSave", DiscountSave);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
