// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SevDesk.Api.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class SaveOrder : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Order model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.Model_Order? Order { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.Model_Order Order { get; set; }
#endif
        /// <summary>The orderPosDelete property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SevDesk.Api.V2.Models.SaveOrder_orderPosDelete? OrderPosDelete { get; set; }
#nullable restore
#else
        public global::SevDesk.Api.V2.Models.SaveOrder_orderPosDelete OrderPosDelete { get; set; }
#endif
        /// <summary>The orderPosSave property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SevDesk.Api.V2.Models.Model_OrderPos>? OrderPosSave { get; set; }
#nullable restore
#else
        public List<global::SevDesk.Api.V2.Models.Model_OrderPos> OrderPosSave { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Models.SaveOrder"/> and sets the default values.
        /// </summary>
        public SaveOrder()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Models.SaveOrder"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SevDesk.Api.V2.Models.SaveOrder CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SevDesk.Api.V2.Models.SaveOrder();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "order", n => { Order = n.GetObjectValue<global::SevDesk.Api.V2.Models.Model_Order>(global::SevDesk.Api.V2.Models.Model_Order.CreateFromDiscriminatorValue); } },
                { "orderPosDelete", n => { OrderPosDelete = n.GetObjectValue<global::SevDesk.Api.V2.Models.SaveOrder_orderPosDelete>(global::SevDesk.Api.V2.Models.SaveOrder_orderPosDelete.CreateFromDiscriminatorValue); } },
                { "orderPosSave", n => { OrderPosSave = n.GetCollectionOfObjectValues<global::SevDesk.Api.V2.Models.Model_OrderPos>(global::SevDesk.Api.V2.Models.Model_OrderPos.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.Model_Order>("order", Order);
            writer.WriteObjectValue<global::SevDesk.Api.V2.Models.SaveOrder_orderPosDelete>("orderPosDelete", OrderPosDelete);
            writer.WriteCollectionOfObjectValues<global::SevDesk.Api.V2.Models.Model_OrderPos>("orderPosSave", OrderPosSave);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
