// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.DocServer.GetTemplatesWithThumb
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Invoice")]
        #pragma warning disable CS1591
        Invoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "invoicereminder")]
        #pragma warning disable CS1591
        Invoicereminder,
        #pragma warning restore CS1591
        [EnumMember(Value = "Order")]
        #pragma warning disable CS1591
        Order,
        #pragma warning restore CS1591
        [EnumMember(Value = "Contractnote")]
        #pragma warning disable CS1591
        Contractnote,
        #pragma warning restore CS1591
        [EnumMember(Value = "Packinglist")]
        #pragma warning disable CS1591
        Packinglist,
        #pragma warning restore CS1591
        [EnumMember(Value = "Letter")]
        #pragma warning disable CS1591
        Letter,
        #pragma warning restore CS1591
        [EnumMember(Value = "Creditnote")]
        #pragma warning disable CS1591
        Creditnote,
        #pragma warning restore CS1591
    }
}
