// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SevDesk.Api.V2.CreditNote.Item.BookAmount;
using SevDesk.Api.V2.CreditNote.Item.ChangeParameter;
using SevDesk.Api.V2.CreditNote.Item.Enshrine;
using SevDesk.Api.V2.CreditNote.Item.GetPdf;
using SevDesk.Api.V2.CreditNote.Item.ResetToDraft;
using SevDesk.Api.V2.CreditNote.Item.ResetToOpen;
using SevDesk.Api.V2.CreditNote.Item.SendBy;
using SevDesk.Api.V2.CreditNote.Item.SendByWithRender;
using SevDesk.Api.V2.CreditNote.Item.SendViaEmail;
using SevDesk.Api.V2.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.CreditNote.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \CreditNote\{creditNoteId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class WithCreditNoteItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bookAmount property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.BookAmount.BookAmountRequestBuilder BookAmount
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.BookAmount.BookAmountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The changeParameter property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.ChangeParameter.ChangeParameterRequestBuilder ChangeParameter
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.ChangeParameter.ChangeParameterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enshrine property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.Enshrine.EnshrineRequestBuilder Enshrine
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.Enshrine.EnshrineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPdf property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.GetPdf.GetPdfRequestBuilder GetPdf
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.GetPdf.GetPdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetToDraft property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.ResetToDraft.ResetToDraftRequestBuilder ResetToDraft
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.ResetToDraft.ResetToDraftRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetToOpen property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenRequestBuilder ResetToOpen
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendBy property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.SendBy.SendByRequestBuilder SendBy
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.SendBy.SendByRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendByWithRender property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.SendByWithRender.SendByWithRenderRequestBuilder SendByWithRender
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.SendByWithRender.SendByWithRenderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendViaEmail property</summary>
        public global::SevDesk.Api.V2.CreditNote.Item.SendViaEmail.SendViaEmailRequestBuilder SendViaEmail
        {
            get => new global::SevDesk.Api.V2.CreditNote.Item.SendViaEmail.SendViaEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCreditNoteItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNote/{creditNoteId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCreditNoteItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNote/{creditNoteId}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes an creditNote
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteDeleteResponse?> DeleteAsWithCreditNoteDeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteDeleteResponse> DeleteAsWithCreditNoteDeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteDeleteResponse>(requestInfo, global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteDeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes an creditNote
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use DeleteAsWithCreditNoteDeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse>(requestInfo, global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a single creditNote
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteGetResponse?> GetAsWithCreditNoteGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteGetResponse> GetAsWithCreditNoteGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteGetResponse>(requestInfo, global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a single creditNote
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWithCreditNoteGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse>(requestInfo, global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a creditNote
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Models.Model_creditNoteResponse"/></returns>
        /// <param name="body">creditNote model</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.Models.Model_creditNoteResponse?> PutAsync(global::SevDesk.Api.V2.Models.Model_creditNoteUpdate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.Models.Model_creditNoteResponse> PutAsync(global::SevDesk.Api.V2.Models.Model_creditNoteUpdate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.Models.Model_creditNoteResponse>(requestInfo, global::SevDesk.Api.V2.Models.Model_creditNoteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes an creditNote
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a single creditNote
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a creditNote
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">creditNote model</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::SevDesk.Api.V2.Models.Model_creditNoteUpdate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::SevDesk.Api.V2.Models.Model_creditNoteUpdate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.CreditNote.Item.WithCreditNoteItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class WithCreditNoteItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class WithCreditNoteItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class WithCreditNoteItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
