// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Tools.BookkeepingSystemVersion
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum BookkeepingSystemVersionGetResponse_objects_version
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "1.0")]
        #pragma warning disable CS1591
        OneZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "2.0")]
        #pragma warning disable CS1591
        TwoZero,
        #pragma warning restore CS1591
    }
}
