// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SevDesk.Api.V2.SevClient.Item.UpdateExportConfig
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class UpdateExportConfigPutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountantClientNumber property</summary>
        public double? AccountantClientNumber { get; set; }
        /// <summary>The accountantNumber property</summary>
        public double? AccountantNumber { get; set; }
        /// <summary>The accountingYearBegin property</summary>
        public double? AccountingYearBegin { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.SevClient.Item.UpdateExportConfig.UpdateExportConfigPutRequestBody"/> and sets the default values.
        /// </summary>
        public UpdateExportConfigPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.SevClient.Item.UpdateExportConfig.UpdateExportConfigPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SevDesk.Api.V2.SevClient.Item.UpdateExportConfig.UpdateExportConfigPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SevDesk.Api.V2.SevClient.Item.UpdateExportConfig.UpdateExportConfigPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountantClientNumber", n => { AccountantClientNumber = n.GetDoubleValue(); } },
                { "accountantNumber", n => { AccountantNumber = n.GetDoubleValue(); } },
                { "accountingYearBegin", n => { AccountingYearBegin = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("accountantClientNumber", AccountantClientNumber);
            writer.WriteDoubleValue("accountantNumber", AccountantNumber);
            writer.WriteDoubleValue("accountingYearBegin", AccountingYearBegin);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
