// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Invoice.Item.SendBy
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Specifies the way in which the invoice was sent to the customer.&lt;br&gt;     Accepts &apos;VPR&apos; (print), &apos;VP&apos; (postal), &apos;VM&apos; (mail) and &apos;VPDF&apos; (downloaded pfd).</summary>
    public enum SendByPutRequestBody_sendType
    {
        [EnumMember(Value = "VPR")]
        #pragma warning disable CS1591
        VPR,
        #pragma warning restore CS1591
        [EnumMember(Value = "VP")]
        #pragma warning disable CS1591
        VP,
        #pragma warning restore CS1591
        [EnumMember(Value = "VM")]
        #pragma warning disable CS1591
        VM,
        #pragma warning restore CS1591
        [EnumMember(Value = "VPDF")]
        #pragma warning disable CS1591
        VPDF,
        #pragma warning restore CS1591
    }
}
