// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SevDesk.Api.V2.Invoice.Factory.CreateInvoiceFromOrder;
using SevDesk.Api.V2.Invoice.Factory.CreateInvoiceReminder;
using SevDesk.Api.V2.Invoice.Factory.SaveInvoice;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SevDesk.Api.V2.Invoice.Factory
{
    /// <summary>
    /// Builds and executes requests for operations under \Invoice\Factory
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class FactoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The createInvoiceFromOrder property</summary>
        public global::SevDesk.Api.V2.Invoice.Factory.CreateInvoiceFromOrder.CreateInvoiceFromOrderRequestBuilder CreateInvoiceFromOrder
        {
            get => new global::SevDesk.Api.V2.Invoice.Factory.CreateInvoiceFromOrder.CreateInvoiceFromOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createInvoiceReminder property</summary>
        public global::SevDesk.Api.V2.Invoice.Factory.CreateInvoiceReminder.CreateInvoiceReminderRequestBuilder CreateInvoiceReminder
        {
            get => new global::SevDesk.Api.V2.Invoice.Factory.CreateInvoiceReminder.CreateInvoiceReminderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saveInvoice property</summary>
        public global::SevDesk.Api.V2.Invoice.Factory.SaveInvoice.SaveInvoiceRequestBuilder SaveInvoice
        {
            get => new global::SevDesk.Api.V2.Invoice.Factory.SaveInvoice.SaveInvoiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Invoice.Factory.FactoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FactoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Invoice/Factory", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Invoice.Factory.FactoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FactoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Invoice/Factory", rawUrl)
        {
        }
    }
}
