// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType
{
    /// <summary>
    /// Builds and executes requests for operations under \Textparser\fetchDictionaryEntriesByType
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class FetchDictionaryEntriesByTypeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FetchDictionaryEntriesByTypeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Textparser/fetchDictionaryEntriesByType?objectName={objectName}{&subObjectName*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FetchDictionaryEntriesByTypeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Textparser/fetchDictionaryEntriesByType?objectName={objectName}{&subObjectName*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve all Placeholders
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeGetResponse?> GetAsFetchDictionaryEntriesByTypeGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder.FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeGetResponse> GetAsFetchDictionaryEntriesByTypeGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder.FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeGetResponse>(requestInfo, global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all Placeholders
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsFetchDictionaryEntriesByTypeGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeResponse?> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder.FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeResponse> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder.FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeResponse>(requestInfo, global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all Placeholders
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder.FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder.FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve all Placeholders
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters 
        {
            /// <summary>Model name</summary>
            [Obsolete("This property is deprecated, use ObjectNameAsGetObjectNameQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("objectName")]
            public string? ObjectName { get; set; }
#nullable restore
#else
            [QueryParameter("objectName")]
            public string ObjectName { get; set; }
#endif
            /// <summary>Model name</summary>
            [QueryParameter("objectName")]
            public global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.GetObjectNameQueryParameterType? ObjectNameAsGetObjectNameQueryParameterType { get; set; }
            /// <summary>Sub model name, required if you have &quot;Email&quot; at objectName</summary>
            [Obsolete("This property is deprecated, use SubObjectNameAsGetSubObjectNameQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subObjectName")]
            public string? SubObjectName { get; set; }
#nullable restore
#else
            [QueryParameter("subObjectName")]
            public string SubObjectName { get; set; }
#endif
            /// <summary>Sub model name, required if you have &quot;Email&quot; at objectName</summary>
            [QueryParameter("subObjectName")]
            public global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.GetSubObjectNameQueryParameterType? SubObjectNameAsGetSubObjectNameQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class FetchDictionaryEntriesByTypeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType.FetchDictionaryEntriesByTypeRequestBuilder.FetchDictionaryEntriesByTypeRequestBuilderGetQueryParameters>
        {
        }
    }
}
