// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.Textparser.FetchDictionaryEntriesByType
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum GetSubObjectNameQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Invoice")]
        #pragma warning disable CS1591
        Invoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "CreditNote")]
        #pragma warning disable CS1591
        CreditNote,
        #pragma warning restore CS1591
        [EnumMember(Value = "Order")]
        #pragma warning disable CS1591
        Order,
        #pragma warning restore CS1591
        [EnumMember(Value = "Contact")]
        #pragma warning disable CS1591
        Contact,
        #pragma warning restore CS1591
        [EnumMember(Value = "Letter")]
        #pragma warning disable CS1591
        Letter,
        #pragma warning restore CS1591
    }
}
