// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.ReceiptGuidance.ForTaxRule
{
    /// <summary>
    /// Builds and executes requests for operations under \ReceiptGuidance\forTaxRule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class ForTaxRuleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForTaxRuleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ReceiptGuidance/forTaxRule?taxRule={taxRule}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForTaxRuleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ReceiptGuidance/forTaxRule?taxRule={taxRule}", rawUrl)
        {
        }
        /// <summary>
        /// You can use this endpoint to get additional information about the tax rule (for example, USTPFL_UMS_EINN) that you may want to use.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleGetResponse?> GetAsForTaxRuleGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder.ForTaxRuleRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleGetResponse> GetAsForTaxRuleGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder.ForTaxRuleRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleGetResponse>(requestInfo, global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// You can use this endpoint to get additional information about the tax rule (for example, USTPFL_UMS_EINN) that you may want to use.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsForTaxRuleGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleResponse?> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder.ForTaxRuleRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleResponse> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder.ForTaxRuleRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleResponse>(requestInfo, global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// You can use this endpoint to get additional information about the tax rule (for example, USTPFL_UMS_EINN) that you may want to use.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder.ForTaxRuleRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder.ForTaxRuleRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// You can use this endpoint to get additional information about the tax rule (for example, USTPFL_UMS_EINN) that you may want to use.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class ForTaxRuleRequestBuilderGetQueryParameters 
        {
            /// <summary>The code of the tax rule you want to get guidance for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("taxRule")]
            public string? TaxRule { get; set; }
#nullable restore
#else
            [QueryParameter("taxRule")]
            public string TaxRule { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class ForTaxRuleRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SevDesk.Api.V2.ReceiptGuidance.ForTaxRule.ForTaxRuleRequestBuilder.ForTaxRuleRequestBuilderGetQueryParameters>
        {
        }
    }
}
