// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SevDesk.Api.V2.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.CreditNote.Item.ResetToOpen
{
    /// <summary>
    /// Builds and executes requests for operations under \CreditNote\{creditNoteId}\resetToOpen
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class ResetToOpenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResetToOpenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNote/{creditNoteId}/resetToOpen", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResetToOpenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNote/{creditNoteId}/resetToOpen", rawUrl)
        {
        }
        /// <summary>
        /// Resets the status &quot;Open&quot; (`&quot;status&quot;: &quot;200&quot;`). Linked transactions will be unlinked.&lt;br&gt;This is not possible if the credit note itself or one of its transactions (CheckAccountTransaction) is already enshrined.This endpoint cannot be used to increase the status to &quot;Open&quot; (`&quot;status&quot;: &quot;200&quot;`).&lt;br&gt;Use [CreditNote/{creditNoteId}/sendBy](#tag/CreditNote/operation/creditNoteSendBy) / [CreditNote/{creditNoteId}/sendViaEmail](#tag/CreditNote/operation/sendCreditNoteViaEMail) instead.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenPutResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SevDesk.Api.V2.Models.ValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenPutResponse?> PutAsResetToOpenPutResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenPutResponse> PutAsResetToOpenPutResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::SevDesk.Api.V2.Models.ValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenPutResponse>(requestInfo, global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Resets the status &quot;Open&quot; (`&quot;status&quot;: &quot;200&quot;`). Linked transactions will be unlinked.&lt;br&gt;This is not possible if the credit note itself or one of its transactions (CheckAccountTransaction) is already enshrined.This endpoint cannot be used to increase the status to &quot;Open&quot; (`&quot;status&quot;: &quot;200&quot;`).&lt;br&gt;Use [CreditNote/{creditNoteId}/sendBy](#tag/CreditNote/operation/creditNoteSendBy) / [CreditNote/{creditNoteId}/sendViaEmail](#tag/CreditNote/operation/sendCreditNoteViaEMail) instead.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SevDesk.Api.V2.Models.ValidationError">When receiving a 422 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsResetToOpenPutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenResponse?> PutAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenResponse> PutAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::SevDesk.Api.V2.Models.ValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenResponse>(requestInfo, global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Resets the status &quot;Open&quot; (`&quot;status&quot;: &quot;200&quot;`). Linked transactions will be unlinked.&lt;br&gt;This is not possible if the credit note itself or one of its transactions (CheckAccountTransaction) is already enshrined.This endpoint cannot be used to increase the status to &quot;Open&quot; (`&quot;status&quot;: &quot;200&quot;`).&lt;br&gt;Use [CreditNote/{creditNoteId}/sendBy](#tag/CreditNote/operation/creditNoteSendBy) / [CreditNote/{creditNoteId}/sendViaEmail](#tag/CreditNote/operation/sendCreditNoteViaEMail) instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.CreditNote.Item.ResetToOpen.ResetToOpenRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class ResetToOpenRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
