// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.CreditNotePos
{
    /// <summary>
    /// Builds and executes requests for operations under \CreditNotePos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class CreditNotePosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreditNotePosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNotePos{?creditNote%5Bid%5D,creditNote%5BobjectName%5D}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreditNotePosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNotePos{?creditNote%5Bid%5D,creditNote%5BobjectName%5D}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve all creditNote positions depending on the filters defined in the query.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNotePos.CreditNotePosGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosGetResponse?> GetAsCreditNotePosGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder.CreditNotePosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosGetResponse> GetAsCreditNotePosGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder.CreditNotePosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosGetResponse>(requestInfo, global::SevDesk.Api.V2.CreditNotePos.CreditNotePosGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all creditNote positions depending on the filters defined in the query.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNotePos.CreditNotePosResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsCreditNotePosGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosResponse?> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder.CreditNotePosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosResponse> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder.CreditNotePosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosResponse>(requestInfo, global::SevDesk.Api.V2.CreditNotePos.CreditNotePosResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all creditNote positions depending on the filters defined in the query.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder.CreditNotePosRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder.CreditNotePosRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve all creditNote positions depending on the filters defined in the query.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class CreditNotePosRequestBuilderGetQueryParameters 
        {
            /// <summary>Retrieve all creditNote positions belonging to this creditNote. Must be provided with creditNote[objectName]</summary>
            [QueryParameter("creditNote%5Bid%5D")]
            public int? CreditNoteid { get; set; }
            /// <summary>Only required if creditNote[id] was provided. &apos;creditNote&apos; should be used as value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("creditNote%5BobjectName%5D")]
            public string? CreditNoteobjectName { get; set; }
#nullable restore
#else
            [QueryParameter("creditNote%5BobjectName%5D")]
            public string CreditNoteobjectName { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class CreditNotePosRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SevDesk.Api.V2.CreditNotePos.CreditNotePosRequestBuilder.CreditNotePosRequestBuilderGetQueryParameters>
        {
        }
    }
}
