// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability
{
    /// <summary>
    /// Builds and executes requests for operations under \Contact\Mapper\checkCustomerNumberAvailability
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class CheckCustomerNumberAvailabilityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CheckCustomerNumberAvailabilityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Contact/Mapper/checkCustomerNumberAvailability{?customerNumber*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CheckCustomerNumberAvailabilityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Contact/Mapper/checkCustomerNumberAvailability{?customerNumber*}", rawUrl)
        {
        }
        /// <summary>
        /// Checks if a given customer number is available or already used.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityGetResponse?> GetAsCheckCustomerNumberAvailabilityGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder.CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityGetResponse> GetAsCheckCustomerNumberAvailabilityGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder.CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityGetResponse>(requestInfo, global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Checks if a given customer number is available or already used.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsCheckCustomerNumberAvailabilityGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityResponse?> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder.CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityResponse> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder.CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityResponse>(requestInfo, global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Checks if a given customer number is available or already used.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder.CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder.CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Checks if a given customer number is available or already used.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters 
        {
            /// <summary>The customer number to be checked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("customerNumber")]
            public string? CustomerNumber { get; set; }
#nullable restore
#else
            [QueryParameter("customerNumber")]
            public string CustomerNumber { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class CheckCustomerNumberAvailabilityRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SevDesk.Api.V2.Contact.Mapper.CheckCustomerNumberAvailability.CheckCustomerNumberAvailabilityRequestBuilder.CheckCustomerNumberAvailabilityRequestBuilderGetQueryParameters>
        {
        }
    }
}
