// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SevDesk.Api.V2.CommunicationWay
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum GetMainQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "0")]
        #pragma warning disable CS1591
        Zero,
        #pragma warning restore CS1591
        [EnumMember(Value = "1")]
        #pragma warning disable CS1591
        One,
        #pragma warning restore CS1591
    }
}
