// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SevDesk.Api.V2.OrderPos.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SevDesk.Api.V2.OrderPos
{
    /// <summary>
    /// Builds and executes requests for operations under \OrderPos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class OrderPosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the sevDesk.Api.V2.OrderPos.item collection</summary>
        /// <param name="position">ID of order position to return</param>
        /// <returns>A <see cref="global::SevDesk.Api.V2.OrderPos.Item.WithOrderPosItemRequestBuilder"/></returns>
        public global::SevDesk.Api.V2.OrderPos.Item.WithOrderPosItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("orderPosId", position);
                return new global::SevDesk.Api.V2.OrderPos.Item.WithOrderPosItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the sevDesk.Api.V2.OrderPos.item collection</summary>
        /// <param name="position">ID of order position to return</param>
        /// <returns>A <see cref="global::SevDesk.Api.V2.OrderPos.Item.WithOrderPosItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::SevDesk.Api.V2.OrderPos.Item.WithOrderPosItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("orderPosId", position);
                return new global::SevDesk.Api.V2.OrderPos.Item.WithOrderPosItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderPosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/OrderPos{?order%5Bid%5D,order%5BobjectName%5D}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderPosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/OrderPos{?order%5Bid%5D,order%5BobjectName%5D}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve all order positions depending on the filters defined in the query.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.OrderPos.OrderPosGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.OrderPos.OrderPosGetResponse?> GetAsOrderPosGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder.OrderPosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.OrderPos.OrderPosGetResponse> GetAsOrderPosGetResponseAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder.OrderPosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.OrderPos.OrderPosGetResponse>(requestInfo, global::SevDesk.Api.V2.OrderPos.OrderPosGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all order positions depending on the filters defined in the query.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.OrderPos.OrderPosResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsOrderPosGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SevDesk.Api.V2.OrderPos.OrderPosResponse?> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder.OrderPosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SevDesk.Api.V2.OrderPos.OrderPosResponse> GetAsync(Action<RequestConfiguration<global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder.OrderPosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SevDesk.Api.V2.OrderPos.OrderPosResponse>(requestInfo, global::SevDesk.Api.V2.OrderPos.OrderPosResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all order positions depending on the filters defined in the query.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder.OrderPosRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder.OrderPosRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve all order positions depending on the filters defined in the query.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class OrderPosRequestBuilderGetQueryParameters 
        {
            /// <summary>Retrieve all order positions belonging to this order. Must be provided with voucher[objectName]</summary>
            [QueryParameter("order%5Bid%5D")]
            public int? Orderid { get; set; }
            /// <summary>Only required if order[id] was provided. &apos;Order&apos; should be used as value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order%5BobjectName%5D")]
            public string? OrderobjectName { get; set; }
#nullable restore
#else
            [QueryParameter("order%5BobjectName%5D")]
            public string OrderobjectName { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class OrderPosRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SevDesk.Api.V2.OrderPos.OrderPosRequestBuilder.OrderPosRequestBuilderGetQueryParameters>
        {
        }
    }
}
